package com.stefanini.model;
// Generated 07/11/2016 12:03:46 by Hibernate Tools 4.3.1.Final

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import javax.persistence.Table;

/**
 * Veiculos generated by hbm2java
 */
@Entity
@Table(name = "veiculos", catalog = "hackathon")
public class Veiculos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "placa", unique = true, nullable = false, length = 8)
	private String placa;
	private String uf;

	//id do modelo
	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "idModelo", nullable = false)
	private Modelo modelo;

	//relacionamento bidirecional com infracoes
	@OneToMany(mappedBy="veiculo")
	private List<Infracoes> infracoes;

	//cpf do proprietario
	@ManyToOne
	@JoinColumn(name = "cpfProprietario", nullable = false)
	private Proprietario proprietario;
	
	public Modelo getModelo() {
		return modelo;
	}

	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	public List<Infracoes> getInfracoes() {
		return infracoes;
	}

	public void setInfracoes(List<Infracoes> infracoes) {
		this.infracoes = infracoes;
	}

	public Veiculos() {
	}



	
	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	

	@Column(name = "uf", nullable = false, length = 2)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	public Proprietario getProprietario() {
		return proprietario;
	}

	public void setProprietario(Proprietario proprietario) {
		this.proprietario = proprietario;
	}

	
	
}
